### PR TITLE
NMS-14522: setcap CAP_NET_BIND_SERVICE on java

### PR DESCRIPTION
**Pull request by RangerRick**
This PR updates the deploy base to run `setcap` on the JDK `java` binary.

### CODE REVIEW

**Comment by RangerRick** [comment]
Note that we will need to do this same thing again in the docker images since we have them do `apt-get upgrade` to get security updates, and it's possible the JDK gets rev'd in that time.

**Comment by dino2gnt** [comment]
The title of the PR does not align with the content.  Did you commit the right things?

**Comment by RangerRick** [comment]
> *edit* nevermind, I am a dummy that can't read.
> 
> I don't know how it works in the container world, but in outside-the-container-land, setting capabilities on the java binary also necessitates adding $JAVA_HOME/lib/jli/ to `ldconfig`, since glibc will disable "insecure" environment variables (e.g. LD_LIBRARY_PATH) on binaries with elevated privs...

Ahh, good catch; that's actually done in some or all of the other docker containers, but I'm not positive it's consistent. I'll add it here to be sure.

**Review by dino2gnt — APPROVED** [review]
Looks tasty.

**Pull request merged**
